### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by sfd1v** [AiekDev/vscode-win7#1]
This is a really great program, but I seem to be having some problems with it. After unzipping and executing it, the icons are turning into boxes.

![Snipaste_2024-03-15_14-59-19](https://github.com/AiekDev/vscode-win7/assets/52351927/ce301633-5456-4b2e-b7f3-23de43016e80)
![Snipaste_2024-03-15_17-00-01](https://github.com/AiekDev/vscode-win7/assets/52351927/10d91889-f1cf-43d7-b241-fd439ebc049e)

**Comment by AiekDev** [comment]
probably caused by Segoe UI font.. this is a issue that is also present in vista
im actually not too sure of what could be, but ive came to the conclusion it could be 1 of 2 things:
1. its caused by the language youve set windows on
2. you dont have this update https://support.microsoft.com/en-us/topic/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-server-2008-r2-is-available-0743a473-3afe-e8b2-7c20-54aa430463d6

if its none, then idk what its caused by lol.. set your language to en-us i guess, worked 4 me

**Comment by sfd1v** [comment]
> 可能是由 Segoe UI 字体引起的。这个问题在 Vista 中也存在， 我实际上不太确定可能是什么，但我得出的结论可能是以下两件事之一：
> 
> 1. 这是由您设置窗口的语言引起的
> 2. 您没有此更新[https://support.microsoft.com/en-us/topic/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-server -2008-r2-is-available-0743a473-3afe-e8b2-7c20-54aa430463d6](https://support.microsoft.com/en-us/topic/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-server-2008-r2-is-available-0743a473-3afe-e8b2-7c20-54aa430463d6)
> 
> 如果没有，那么我不知道它是由什么引起的，哈哈..将你的语言设置为 en-us 我猜，对我有用 4



> probably caused by Segoe UI font.. this is a issue that is also present in vista im actually not too sure of what could be, but ive came to the conclusion it could be 1 of 2 things:
> 
> 1. its caused by the language youve set windows on
> 2. you dont have this update https://support.microsoft.com/en-us/topic/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-server-2008-r2-is-available-0743a473-3afe-e8b2-7c20-54aa430463d6
> 
> if its none, then idk what its caused by lol.. set your language to en-us i guess, worked 4 me

Thank you very much for your reply. I actually prefer v1.85.2, but the "Remote - SSH" plugin doesn't work in this version, I tried to fix it, but it took me 3 days.

**Comment by sfd1v** [comment]
> probably caused by Segoe UI font.. this is a issue that is also present in vista im actually not too sure of what could be, but ive came to the conclusion it could be 1 of 2 things:
> 
> 1. its caused by the language youve set windows on
> 2. you dont have this update https://support.microsoft.com/en-us/topic/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-server-2008-r2-is-available-0743a473-3afe-e8b2-7c20-54aa430463d6
> 
> if its none, then idk what its caused by lol.. set your language to en-us i guess, worked 4 me

 Thank you very much for your reply. I actually prefer v1.85.2, but the "Remote - SSH" plugin doesn't work in this version, I tried to fix it but wasted 3 days. so i have to choose v1.87.2.

**Comment by fulei623** [comment]
I solved this problem.  
you need to install the Windows6.1-KB2670838-x64 patch

**Comment by AiekDev** [comment]
there was a simpler patch using windows 11's segoe ui's font which also gave you proper emojies, but it broke a lot of stuff. idk where it is i dont have it anymore
